### ISSUE TITLE
Rafraichir la géolocalisation

### ISSUE THREAD

**Issue by antoinemaz** [moreaupierrick/WonderFuel#1]
But : rafraichir la géolocalisation à l'aide d'un timeout.

Lien : https://thedotproduct.org/example-of-navigator-geolocation-watchposition/

**Comment by moreaupierrick** [comment]
done. en utilisant la methode watchPosition à la place de getCurrentPosition, la position se met à jour plus fréquement :)

**Comment by moreaupierrick** [comment]
j'ai pas fait attention mais quand la géolocalisation se met à jour, cela recharge tout. Il faut que cela ne rechercharge que le marker de notre position. Fiche rouverte.
