### ISSUE TITLE
Cercle de recherche

### ISSUE THREAD

**Issue by antoinemaz** [moreaupierrick/WonderFuel#13]
But : permettre d'ajouter un cercle de recherche pour tracer le périmètre

Lien : http://leafletjs.com/examples/quick-start.html

**Comment by moreaupierrick** [comment]
done. j'ai mis un cercle de 5km de diamètre par défaut. Si on souhaite que l'utilisateur choisisse son rayon d'action, on créer une autre fiche qui permet à l'utilisateur de choisir sa distance max.
