### ISSUE TITLE
Afficher la div d'infos avec un bouton "Rechercher les stations"

### ISSUE THREAD

**Issue by antoinemaz** [moreaupierrick/WonderFuel#2]
But : afficher descriptif du projet et un bouton "Rechercher les stations"

Lien : https://developers.google.com/maps/documentation/javascript/examples/save-widget

**Comment by moreaupierrick** [comment]
"Recherche les stations" -> "Start"

**Comment by moreaupierrick** [comment]
@antoinemaz, je récupère la fiche étant donné que tu travaille actuellement sur la recupération du fichier XML de data.gouv.fr
