### ISSUE TITLE
Ajout d'un formulaire de recherche dans les filtres

### ISSUE THREAD

**Issue by moreaupierrick** [moreaupierrick/WonderFuel#20]
Une question que je vous pose : 
- Imaginons que l'utilisateur souhaite ne pas voir les stations essences autour de sa position mais aux alentours d'une ville dans lequel il va aller... pour palier à ce besoin, on pourrait ajouter dans les filtres un champ de recherche dans lequel on saisie une adresse ou une ville et du coup on cherchera autour de cette ville et non sa position.

Qu'en pensez vous ?

**Comment by antoinemaz** [comment]
Ca dépend du besoin initial, ça été demandé par Didier ? Si oui, bah on le fait, si non, on ne le fait pas.

**Comment by moreaupierrick** [comment]
étant donné que c'est un projet from scratch, on fais tout ce qu'on veut. Après je pense que ce serait intéressant de demander au prof quels besoins il  aimerait dans l'application. ça nous permettrait de la rendre plus complète qu'elle ne l'est déjà.

**Comment by antoinemaz** [comment]
Contentons nous de ce qu'il y a déjà à développer ;) Plus tôt sera fini le projet, mieux se sera. On a un beau mémoire à commencer d'ailleurs :p

Après toi si tu veux ajouter autres choses vas-y, mais je t'avoue que personnellement, je ne suis pas pour ajouter d'autres fonctionnalités, mis à part si ce sont des corrections ou éventuellement des toutes petites évolutions.
